{% set version = "2021.8.0" %}

package:
  name: jupyter-repo2docker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-repo2docker/jupyter-repo2docker-{{ version }}.tar.gz
  sha256: 9d1b3c3ec7944ea6b0a234d6fa77293a2d1ed1c080eba8466aba94f811b3465d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-repo2docker = repo2docker.__main__:main
    - repo2docker = repo2docker.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docker-py
    - escapism
    - jinja2
    - python-json-logger
    - requests
    - ruamel.yaml >=0.15
    - semver
    - toml
    - traitlets

test:
  imports:
    - repo2docker
    - repo2docker.buildpacks
    - repo2docker.buildpacks.conda
    - repo2docker.buildpacks.legacy
    - repo2docker.buildpacks.python
  commands:
    - pip check
    - jupyter-repo2docker --help
    - repo2docker --help
  requires:
    - pip

about:
  home: https://repo2docker.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Repo2docker: Turn code repositories into Jupyter enabled Docker Images'

extra:
  recipe-maintainers:
    - ocefpaf
