{% set version = "0.7.0" %}

package:
  name: jupyter-repo2docker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-repo2docker/jupyter-repo2docker-{{ version }}.tar.gz
  sha256: cf93ddf283de8c6b8f4ad983f8bf9b7b2a2c37812e387c245f8ba229d4f180c4

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - jupyter-repo2docker = repo2docker.__main__:main
    - repo2docker = repo2docker.__main__:main

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4
    - docker-py
    - escapism
    - jinja2
    - python-json-logger
    - ruamel.yaml >=0.15
    - traitlets

test:
  imports:
    - repo2docker
    - repo2docker.buildpacks
    - repo2docker.buildpacks.conda
    - repo2docker.buildpacks.legacy
    - repo2docker.buildpacks.python
  commands:
    - jupyter-repo2docker --help
    - repo2docker --help

about:
  home: https://repo2docker.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Repo2docker: Turn code repositories into Jupyter enabled Docker Images"

extra:
  recipe-maintainers:
    - ocefpaf
