{% set version = "2023.6.0" %}

package:
  name: jupyter-repo2docker
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter-repo2docker/jupyter-repo2docker-{{ version }}.tar.gz
  sha256: 72e01a5b441d81ba6c9417a9831e1fccab6e98d5c9362b74eae4792faa07009d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - jupyter-repo2docker = repo2docker.__main__:main
    - repo2docker = repo2docker.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - chardet
    - docker-py !=5.0.0
    - entrypoints
    - escapism
    - iso8601
    - jinja2
    - python-json-logger
    - requests
    - ruamel.yaml >=0.15
    - semver
    - toml
    - traitlets

test:
  imports:
    - repo2docker
    - repo2docker.buildpacks
  commands:
    - pip check
    - jupyter-repo2docker --help
    - repo2docker --help
  requires:
    - pip

about:
  home: https://repo2docker.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Repo2docker: Turn code repositories into Jupyter enabled Docker Images'

extra:
  recipe-maintainers:
    - ocefpaf
