{% set version = "2025.8.0" %}

package:
  name: jupyter-repo2docker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyter-repo2docker/jupyter_repo2docker-{{ version }}.tar.gz
  sha256: 88df9146a5e596cf6c1dec1bf41a44abc1452da1689dd0dc692569888adf05ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - jupyter-repo2docker = repo2docker.__main__:main
    - repo2docker = repo2docker.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - chardet
    - docker-py !=5.0.0
    - entrypoints
    - escapism
    - iso8601
    - jinja2
    - python-json-logger
    - requests
    - ruamel.yaml >=0.15
    - semver
    - toml
    - traitlets

test:
  imports:
    - repo2docker
    - repo2docker.buildpacks
  commands:
    - pip check
    - jupyter-repo2docker --help
    - repo2docker --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://repo2docker.readthedocs.io/en/latest/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Repo2docker: Turn code repositories into Jupyter enabled Docker Images'

extra:
  recipe-maintainers:
    - ocefpaf
