travis:
  secure:
    BINSTAR_TOKEN: QEG1lOkDEFRa6T+DvDyPBfNX25zrB4vwQpkMy/XPOtni04LOK2DBvAiwc5kGRJB5bY5gaBwxQkd+kQ8Kq6DxZryw+hv6dThnvp2mGtZxtDlaIuP85n1D/u5CXQGoQ8VLEhHbvcWjxRCv7AsC26w+xgoqdaUs84vY6JNcaclKgf2CO4+3c4ibHmZWuT0gkcWyjIYj72rT0KXTvwNyNMfTEbEYCV/lolkmb74tlksCPkZkRrt0lYXCAiy7OEOgPaxbFmo2O0EU0S8qXhEFm/KVFBpv8ZS3/SDUyocRJaEPMW9uDrIl7EFHO076fLQmD9j8V6HQkKoeL7BIqzCSKgiu1/LIhIv9OzpVVjEj8R13uq/52W2x+E8yiBtoIqfNYK3PPwothZKVQJLhseeayDNCnlONFGDMTK/CdTfu8hnq6LemRLlVpB7n6KxZQ6vNGTAKwFeHW5UMpNoLB7yL5BynXjhp9NXnFpnhK/TANIAixzkFWSoiAU4mobDmJ6KCr/EqTXEFRCYcHjmWt1NyNGvE7l/JWkSLYSv5dsRAhoNKJkNfnWTDCVzI3lVZUevMAMVDlGJGYqDhMfMOcudvX3hFWwTXno5JRE0fEOqNyW25ZN5DmzN5rjJ600PWm6iYPuEUmIaDh0XFzWNmsBG2P0JkLDMEDjy6Uhx976VYwmEbteM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
